POST https://localhost:8080/register
Content-Type: application/json

{
    "email":"is714719@iteso.mx",
    "psswd":"123456",
    "nombre":"Ruvo"
}

###

POST https://localhost:8080/login
Content-Type: application/json

{
    "email":"is714719@iteso.mx",
    "psswd":"123456"
}

###

GET https://localhost:8080/files
###

POST https://localhost:8080/edit
Content-Type: application/json

{
    "email":"is714719@iteso.mx",
    "psswd":"123456",
    "newemail":"is714719@iteso.mx",
    "newnombre":"RuvA"
}